### ISSUE TITLE
jme3-desktop dependency is missing on desktop project

### ISSUE THREAD

**Issue by Ali-RS** [jMonkeyEngine/jme-initializer#7]
Desktop projects `build.gradle` does not include jme3-desktop dependency which is essential for running the app.

**Comment by richardTingle** [comment]
Thanks for noticing this. I've pushed a correction. The release has to be kicked off manually so I'll request that once the question of the assets folder is finalised

**Comment by Ali-RS** [comment]
Ok, thank you.

**Comment by richardTingle** [comment]
This fix has now been released. Closing the issue.
